language: node_js
node_js: 11.10.0
os:
- linux
before_script:
- npm install -g gulp
script: gulp

cache:
  directories:
    - "node_modules"

before_deploy:
  - pwd
  - ls dist/js/
  
deploy:
  provider: releases
  api_key:
    secure: "kTGRj3VZoWDWpC9BS6R5b/+iw1d63HLzxTia4IOzu3RHBzg3xXWKtrh/27YbsNRSgZVwyKBim3jZzc/DQV+9TWjJ5uWoqQrJGzbQFUtSheOdK43eJIe7knXwln/HKNsA0Dhj80JAI3nC9IkeQpG4P9RsRhoZd2pCTdQD5heWiwqW3VCrPeWctZeHujTxxxOMlCh47IdiNRfBxaTPpTKd0mWhIawbLbHHccSdbiI/+ciBx5Ty27msP/NalN4YRs4WDVgwvM+FzHcPFuNw/CKrhWf5WUGxJDIKdfs6HghrRWHPp5mAUQvj+NYd59v+bwhR7nRLjjht5ioQbe83DlyamLcYp2VXcVinX8Dr/uh+FayHDLqqy6z+Hv9ax4nlfU3SP9vV6MtTgvjn7aMbxgcoZkNoSjRsi6O4e9Dybg/ski2t21Wgyh0MSa5wCt6CV6sBvv0+nBK2QcJtmI5ojgvTclZSv8aXLJySG22u/yU0irZzkcUM6z2JoskjCE95vNmoVDVl55ANN5kShQKCbRbV/teLzULnk1ZlI3WeNmHCcjVg0SKB4f5baAI0HcU6Y6YbNyJdhIPf7l78NlPwM/2WkHB9U7VbgV4ZpY/Gqg3xMhsaU5c6+HLw7heNeEHXuLhK2NEqv/bbcLyobBJtOPDoJ+cTCQCPGpekW2Fj2WnbE6U="
  file: dist/js/popman.min.js
  skip_cleanup: true
  on:
    repo: sj-js/popman
    branch: master